# Generated by Django 4.2.3 on 2023-07-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperequirement',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
