# Generated by Django 4.2.3 on 2023-07-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_reciperequirement_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
